import { preload } from 'react-dom'

import type { Media } from '@/payload-types'

type Props = {
  media: Media | null | undefined
  alt?: string
  sizes: string
  className?: string
  priority?: boolean
}

// Uses Payload's pre-generated WebP sizes instead of an image optimizer
export function ProductImage({ media, alt, sizes, className = '', priority }: Props) {
  if (!media?.url) return <ImagePlaceholder className={className} />

  const sources = [
    media.sizes?.thumbnail?.url && `${media.sizes.thumbnail.url} ${media.sizes.thumbnail.width}w`,
    media.sizes?.card?.url && `${media.sizes.card.url} ${media.sizes.card.width}w`,
    `${media.url} ${media.width}w`,
  ].filter(Boolean)

  if (priority) {
    preload(media.sizes?.card?.url || media.url, {
      as: 'image',
      imageSrcSet: sources.join(', '),
      imageSizes: sizes,
      fetchPriority: 'high',
    })
  }

  return (
    // eslint-disable-next-line @next/next/no-img-element -- responsive sizes are pre-generated by Payload
    <img
      src={media.sizes?.card?.url || media.url}
      srcSet={sources.join(', ')}
      sizes={sizes}
      width={media.width ?? undefined}
      height={media.height ?? undefined}
      alt={alt ?? media.alt}
      loading={priority ? 'eager' : 'lazy'}
      fetchPriority={priority ? 'high' : undefined}
      decoding={priority ? 'sync' : 'async'}
      className={`object-cover ${className}`}
    />
  )
}

export function ImagePlaceholder({ className = '' }: { className?: string }) {
  return (
    <div className={`flex items-center justify-center bg-sand text-beige-dark ${className}`}>
      <svg
        viewBox="0 0 48 48"
        className="h-12 w-12"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.2"
        aria-hidden
      >
        <circle cx="24" cy="28" r="12" />
        <path d="M18 14l6-6 6 6-6 4z" />
      </svg>
    </div>
  )
}
